"""Generates the predictive-model script that Epiphany commits via GitLab.

The script is rendered from the *validated* hypothesis so the committed asset is
traceable to the statistics that justified it, and it mirrors what
:mod:`app.services.model_trainer` actually trained: a scikit-learn pipeline that
predicts the validated ``target`` from the dataset's numeric + categorical
columns. It is fully driven by the proven ``feature``/``target`` — nothing is
hard-coded to a particular column — and stays inside the sandbox's
``MODEL_ALLOWED_MODULES`` allowlist so it passes the AST security screen before
deployment.
"""

from __future__ import annotations

import re
from typing import Any


def _safe_ident(name: str, fallback: str = "target") -> str:
    """Turn an arbitrary column name into a valid Python identifier fragment."""
    cleaned = re.sub(r"\W+", "_", str(name)).strip("_").lower()
    if not cleaned or not re.match(r"[a-z_]", cleaned):
        cleaned = f"{fallback}_{cleaned}".strip("_")
    return cleaned or fallback


def model_filename(hypothesis: dict[str, Any]) -> str:
    """Deterministic, target-derived filename for the generated asset."""
    target = _safe_ident(hypothesis.get("target", "target"), "target")
    return f"predict_{target}.py"


def render_model_script(hypothesis: dict[str, Any]) -> str:
    """Render a runnable scikit-learn training script for the validated target."""
    feature = hypothesis.get("feature", "feature")
    target = hypothesis.get("target", "target")
    statement = hypothesis.get("statement", "")
    validation = hypothesis.get("validation", {})
    test = validation.get("test", "n/a")
    p_value = validation.get("p_value", "n/a")
    statistic = validation.get("statistic", "n/a")
    model = hypothesis.get("model", {})
    task = model.get("task", "classification")
    metrics = model.get("metrics", {})
    func = f"train_{_safe_ident(target)}_model"

    if task == "regression":
        est_import = "from sklearn.ensemble import GradientBoostingRegressor as Estimator"
        target_cast = "y = pd.to_numeric(df[TARGET], errors=\"coerce\")"
    else:
        est_import = "from sklearn.ensemble import GradientBoostingClassifier as Estimator"
        target_cast = "y, _ = pd.factorize(df[TARGET])"

    return f'''"""Autonomous predictive model generated by Epiphany.

Validated hypothesis: {statement}
Evidence: {test} → statistic={statistic}, p={p_value}
Key driver surfaced during exploration: `{feature}` → `{target}`.
Measured performance (held-out): {metrics or "see report"}.

This asset was authored automatically from a statistically significant
discovery (p < 0.05) and opened as a Merge Request for human review.
"""

import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
{est_import}

TARGET = "{target}"


def {func}(df: pd.DataFrame) -> Pipeline:
    """Train a model that predicts `{target}` from the dataset."""
    df = df.dropna(subset=[TARGET]).copy()
    {target_cast}

    features = [c for c in df.columns if c != TARGET]
    numeric = [c for c in features if pd.api.types.is_numeric_dtype(df[c])]
    categorical = [
        c for c in features
        if not pd.api.types.is_numeric_dtype(df[c]) and df[c].nunique() <= 20
    ]

    pre = ColumnTransformer([
        ("num", Pipeline([
            ("impute", SimpleImputer(strategy="median")),
            ("scale", StandardScaler()),
        ]), numeric),
        ("cat", Pipeline([
            ("impute", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore", max_categories=20)),
        ]), categorical),
    ], remainder="drop")

    pipeline = Pipeline([("prep", pre), ("model", Estimator(random_state=42))])

    X_train, X_test, y_train, y_test = train_test_split(
        df[numeric + categorical], y, test_size=0.2, random_state=42
    )
    pipeline.fit(X_train, y_train)
    print("Test score:", pipeline.score(X_test, y_test))
    return pipeline


# Usage:
#   import pandas as pd
#   from {model_filename(hypothesis)[:-3]} import {func}
#   model = {func}(pd.read_csv("data/train.csv"))
'''
